server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tunishop_bd
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
  mail:
    host: smtp.gmail.com 
    port: 587
    username: zak.saafi@gmail.com
    password: qgqbihkmowqndcsy
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true     
              
    
  jackson:
    serialization:
      fail-on-empty-beans: false
      

  servlet:
    multipart:
      max-file-size: 10000000000MB
      max-request-size: 10000000000MB
             

        
